# Generated by Django 4.0 on 2022-12-23 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exampleapp', '0005_alter_cost_invoice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='vehicle',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='exampleapp.vehicle'),
        ),
    ]
