# Generated by Django 4.0 on 2022-12-23 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exampleapp', '0006_insurance_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('begin', models.CharField(max_length=100)),
                ('end', models.CharField(max_length=100)),
                ('distance', models.IntegerField(max_length=4)),
            ],
        ),
    ]
