# Generated by Django 4.0 on 2022-12-26 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exampleapp', '0009_alter_address_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('street', 'postal_code', 'city', 'type')},
        ),
    ]
