# Generated by Django 4.0 on 2022-12-26 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exampleapp', '0010_alter_address_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractor',
            name='id',
        ),
        migrations.AlterField(
            model_name='contractor',
            name='address',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='exampleapp.address'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='nip',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
