# Generated by Django 4.0 on 2022-12-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exampleapp', '0012_alter_contractor_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='nip',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
