# Generated by Django 4.0 on 2022-12-26 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exampleapp', '0013_alter_contractor_nip'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contractor',
            unique_together={('nip', 'address')},
        ),
    ]
