# Generated by Django 4.0 on 2022-12-26 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exampleapp', '0014_alter_contractor_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='address', to='exampleapp.address'),
        ),
    ]
