# Generated by Django 4.0 on 2022-12-26 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exampleapp', '0017_alter_contractor_country_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('pesel', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('driver_license_number', models.CharField(max_length=100, unique=True)),
                ('date_qualification_certificate', models.DateField()),
                ('date_bhp_course', models.DateField()),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='address_driver', to='exampleapp.address')),
            ],
        ),
    ]
