# Generated by Django 4.0 on 2023-01-07 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exampleapp', '0018_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='exampleapp.address'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_driver', to='exampleapp.address'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='pesel',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, unique=True),
        ),
    ]
