# Generated by Django 4.0 on 2023-01-07 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exampleapp', '0020_alter_driver_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address_driver', to='exampleapp.address'),
        ),
    ]
