# Generated by Django 4.0 on 2023-01-07 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exampleapp', '0021_alter_driver_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='exampleapp.address'),
        ),
    ]
