# Generated by Django 4.0 on 2023-01-07 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exampleapp', '0022_alter_contractor_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='contractor',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contractor', to='exampleapp.contractor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='driver',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='exampleapp.driver'),
        ),
        migrations.AddField(
            model_name='route',
            name='vehicle',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='exampleapp.vehicle'),
            preserve_default=False,
        ),
    ]
