# Generated by Django 4.0 on 2023-01-07 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exampleapp', '0023_route_contractor_route_driver_route_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor', to='exampleapp.contractor'),
        ),
        migrations.AlterField(
            model_name='route',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='exampleapp.driver'),
        ),
        migrations.AlterField(
            model_name='route',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='exampleapp.vehicle'),
        ),
    ]
