# Generated by Django 4.0 on 2023-01-07 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exampleapp', '0028_alter_settlement_driver'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='settlement',
            unique_together={('month', 'year', 'driver')},
        ),
    ]
