# Generated by Django 4.0 on 2023-01-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exampleapp', '0031_alter_settlement_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='kilometers_done',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
